### ISSUE TITLE
Nginx.updateHostsConfigurationScript uses wrong comparison

### ISSUE THREAD

**Issue by krzyk** [yegor256/thindeck#415] opened 2014-11-03 14:54 UTC
Right now we have in code:
```
                "then if [[ $(grep '%s:%d' %s.hosts.conf) != *%s:%d* ]]",
```

This won't work, should be changed to something like ``"then if !grep -q '%s:%d' %s.hosts.conf" ``

**Comment by krzyk** [comment] 2015-01-01 09:04
@nathansgreen basically after code has been merged you have to use "@" + nick of the person that opened the ticket and ask him to close it, you informed davvd about it, not me. Look at other issues and how they were closed.

**Comment by php-coder** [comment] 2015-01-01 16:24
As far I can see @nathansgreen already have fixed this bug in his commit bb3d96bc1a890

@krzyk could you close this task?

**Comment by davvd** [comment] 2015-01-05 13:44
@php-coder please don't touch this task, someone else will pick it up, thanks

**Comment by davvd** [comment] 2015-01-05 14:46
@peterarsentev the task is yours,please go ahead

**Comment by peterarsentev** [comment] 2015-01-06 14:45
@krzyk Right now it looks good.

then if ! ( grep -q 'server3:456' host3.hosts.conf );

This is output from tests and It runs correctly in bash shell on my linux.
One more. it was changed on Guava lib from String.format.
I guess somebody fixed it already.
if it is ok please close the ticket.

**Closed** 2015-01-06 15:46 UTC
Labels: 30 mins, @peterarsentev, bug, DEV, TS/FIX

**Comment by davvd** [comment] 2015-01-07 17:51
@peterarsentev paid, thanks, added **30 mins** to your account, payment `49963844`

+30 added to your rating, current score is: [+45](http://www.netbout.com/b/35098?open=rating)

**Comment by nathansgreen** [comment] 2015-01-08 05:46
@yegor256 I see from #404 that you keep multiple double-standards. You re-assigned @php-coder to a task that was taken from him, even though his pull request was still open. You make team members responsible both for themselves and the project managers, but with project managers that responsibility is not reciprocal. The double-standards are evident.

You accept work by merging pull requests, then claim the work isn’t really done. If paying for work is all or nothing, accepting work must be all or nothing.

If someone approves a pull request and the problem isn’t solved, that’s a mistake, and it carries a cost. I will not carry the cost of others’ mistakes. Doing so is the antithesis of a no obligations principle.

**Comment by yegor256** [comment] 2015-01-08 10:31
@nathansgreen sometimes we make mistakes, you're right. Each time we're trying to fix our mistakes. Your job is to protect yourself in all this chaos and you're doing it right :) For the future, every time you see a problem like that, just say explicitly what you want us to do. For example: "give this task back to me". In most cases we won't argue and will do that.

**Comment by yegor256** [comment] 2015-01-08 10:31
@davvd please add extra 30 mins to @nathansgreen, he obviously was the resolver of this issue

**Comment by davvd** [comment] 2015-01-08 14:26
> @davvd please add extra 30 mins to @nathansgreen, he obviously was the resolver of this issue

@yegor256 I've sent 30 mins extra to @nathansgreen in transaction ID "AP-85D93611L6231593J"
