### ISSUE TITLE
doc.thindeck.com fails to display the logo

### ISSUE THREAD

**Issue by adko-pl** [yegor256/thindeck#481] opened 2014-12-21 19:27 UTC
The technical documentation page (http://doc.thindeck.com/) fails to display the logo on the top.

**Comment by davvd** [comment] 2015-01-06 18:52
@maurezen this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by maurezen** [comment] 2015-01-06 20:32
The link to .svg logo is incorrect in layout file. Please provide a live link to .svg logo file. Alternatively I can use .png logo at http://www.thindeck.com/logo-512x512.png . Or are we talking about teamed logo (http://img.teamed.io/logo.svg)?

**Comment by yegor256** [comment] 2015-01-06 20:38
@maurezen use the PNG URL one you mentioned. We don't have a proper SVG at the moment

**Comment by maurezen** [comment] 2015-01-06 20:59
Created a pull request here #487

**Comment by maurezen** [comment] 2015-01-10 11:43
@adko-pl pull request #487 merged, please close the issue.

**Closed** 2015-01-10 12:29 UTC
Labels: 30 mins, @maurezen, bug, DEV

**Comment by davvd** [comment] 2015-01-13 16:17
@maurezen Many thanks! **30 mins** were added to your account in Transaction ID `50216303`. added +30 to your rating, now it is equal to [+330](http://www.netbout.com/b/35102?open=rating)
